blueprint:
  name: "AVA Turn on screen saver"
  author: "Lone baggie"
  homeassistant:
    min_version: 2024.6.0
  description: >
    ### 📺 Turn on screen saver. This blueprint relies on all AVA entities to have the same name as the AVA device
    they belong too. So switch.xxx_screensaver_display must match the device name xxx.
    
  domain: automation 
  input:
    fallback_media_player:
      name: Fallback Speaker
      description: The speaker to use if no speaker found.
      selector:
        entity:
          filter:
            - domain: media_player
    screen_saver_url:
      name: URL of screen saver
      description: URL
      selector:
        text:
    # --- Collapsible Voice Phrases Section with Syntax Guide ---
    voice_command_options:
      name: Voice Phrases
      icon: mdi:account-voice
      collapsed: false
      description: >
        Custom voice sentences that will trigger screen saver on.

        <br>

        <details>
          <summary><b>ℹ️ Click to view the Voice Command Syntax Guide</b></summary>
          <br>
          When editing the phrases below, use these rules to tweak your phrases:
          
          * <b>[Square Brackets]</b> = Optional words. Matches with or without them.
            * *Example:* `[what is] the weather` matches both "the weather" and "what is the weather".
            
          * <b>(Pipes | inside | parentheses)</b> = Alternative words (OR). Matches any single phrase.
            * *Example:* `(tell me|give me)` matches "tell me..." or "give me...".
        </details>
      input:
        screen_sentence:
          name: Screen saver command 
          description: The phrase to turn on Screen saver
          default: "Turn on [the] screen saver [now]"
          selector:
            text:


mode: single

trigger:
  - trigger: conversation
    command:
      - !input screen_sentence

condition: []

action:

  - variables:
      fallback_player: !input fallback_media_player
      # Find out which physical room sent the trigger to target the closest local speaker
      sat: "{{trigger.satellite_id.split('.')}}"
      switch: switch.{{sat[1]}}_screensaver_display
      default: !input fallback_media_player
      speaker: >
        {% if sat[1] != "" %}
          media_player.{{sat[1]}}
        {% else %}
          {{default}}
        {% endif %}
      text: text.{{sat[1]}}_screensaver_url
      url: !input screen_saver_url

  - action: text.set_value
    metadata: {}
    target:
      entity_id: "{{text}}"
    data:
      value: "{{url}}"
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: "{{switch}}"
    data: {}
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: "{{switch}}"
    data: {}
  
