blueprint:
  name: "AVA Turn on screensaver"
  author: "Lone baggie"
  homeassistant:
    min_version: 2024.6.0
  description: >
    ### 📺 Turn on screen saver
    This blueprint relies on all AVA entities to have the same name as the AVA device
    they belong to. So `switch.xxx_screensaver_display` must match the device name `xxx`.

  domain: automation
  input:
    voice_command_options:
      name: Voice Phrases
      icon: mdi:account-voice
      collapsed: false
      description: >
        Custom voice sentences that will trigger screen saver on.

        <br>

        <details>
          <summary><b>ℹ️ Click to view the Voice Command Syntax Guide</b></summary>
          <br>
          When editing the phrases below, use these rules to tweak your phrases:
          
          * <b>[Square Brackets]</b> = Optional words. Matches with or without them.
            * *Example:* `[what is] the weather` matches both "the weather" and "what is the weather".
            
          * <b>(Pipes | inside | parentheses)</b> = Alternative words (OR). Matches any single phrase.
            * *Example:* `(tell me|give me)` matches "tell me..." or "give me...".
        </details>
      input:
        screen_sentence:
          name: Screen saver command
          description: The phrase(s) to turn on the screen saver.
          default:
            - "(display|start|open|) [the] screen saver [now]"
            - "(display|start|open|) [the] screensaver [now]"
          selector:
            text:
              multiple: true

mode: single

trigger:
  - trigger: conversation
    command: !input screen_sentence

condition: []

action:
  - variables:
      entity: "{{ trigger.satellite_id }}"
      device: "{{ device_name(entity) if entity is not none else '' }}"
      switch_ss: "switch.{{ device }}_screensaver_display"

  # Ensure a valid satellite triggered this before trying to toggle the switch
  - if:
      - condition: template
        value_template: "{{ entity is not none and device != '' }}"
    then:
      - action: switch.turn_on
        target:
          entity_id: "{{ switch_ss }}"
      - set_conversation_response: "Turning on screensaver"