blueprint:
  name: AVA Screen Manager
  author: Lone baggie
  homeassistant:
    min_version: 2024.6.0
  description: >
    ### AVA controls Broswer screen timeouts.
  domain: automation
  input:
    target_switches:
      name: Trigger Switches
      description: Select one or more ESPHome switches to trigger this automation.
      selector:
        entity:
          filter:
            domain: switch
            integration: esphome
          multiple: true
    delay_time:
      name: Delay Time
      description: How long the trigger switch must remain ON before taking action.
      default:
        hours: 0
        minutes: 0
        seconds: 20
      selector:
        duration: {}

mode: single

trigger:
  - platform: state
    entity_id: !input target_switches
    to: "on"
    for: !input delay_time

condition: []

action:
  - variables:
      entity: "{{ trigger.entity_id }}"
      device: "{{ device_name(entity) }}"
      switch_ss: "switch.{{ device }}_screensaver_display"
      text_br: "text.{{ device }}_remote_browser_url"

  - action: text.set_value
    target:
      entity_id: "{{ text_br }}"
    data:
      value: " "

  - action: switch.turn_on
    target:
      entity_id: "{{ switch_ss }}"
    data: {}