blueprint:
  name: "AVA Display the time "
  author: "Lone baggie"
  homeassistant:
    min_version: 2024.6.0
  description: >
    ### 🕰 Displays clock on display. blueprint relies on the music assistant
    media players have the same name as the AVA device. So media_player.xxx must match the device name xxx.
  domain: automation 
  input:
    fallback_media_player:
      name: Fallback Speaker
      description: The speaker to use if no satellite location is detected.
      selector:
        entity:
          filter:
            - domain: media_player

    html:
      name: HTML display
      description: Enter URL of page to display on device. 
      default: http://192.168.0.254:8123/local/clock.html
      selector:
        text:
    voice_command_options:
      name: Voice Phrases
      icon: mdi:account-voice
      collapsed: false
      description: >
        Custom voice sentences that will trigger this weather report.

        <br>

        <details>
          <summary><b>ℹ️ Click to view the Voice Command Syntax Guide</b></summary>
          <br>
          When editing the phrases below, use these rules to tweak your phrases:
          
          * <b>[Square Brackets]</b> = Optional words. Matches with or without them.
            * *Example:* `[what is] the weather` matches both "the weather" and "what is the weather".
            
          * <b>(Pipes | inside | parentheses)</b> = Alternative words (OR). Matches any single phrase.
            * *Example:* `(tell me|give me)` matches "tell me..." or "give me...".
        </details>
      input:
        time_sentence_1:
          name: Time Command 
          description: The primary phrase used to display the clock.
          default: "show [me] the (time|clock)"
          selector:
            text:
        time_sentence_2:
          name: Secondary time Command 
          description: The secondary phrase to display the clock.
          default: "display [the] (time|clock)"
          selector:
            text:
mode: single

trigger:
  - trigger: conversation
    command:
      - !input time_sentence_1
      - !input time_sentence_2

condition: []

action:

  - variables:
      sat: "{{trigger.satellite_id.split('.')}}"
      default: !input fallback_media_player
      url: !input html
      speaker: >
        {% if sat[1] != "" %}
          media_player.{{sat[1]}}
        {% else %}
          {{default}}
        {% endif %}
      switch: switch.{{sat[1]}}_browser_display
      text: text.{{sat[1]}}_remote_browser_url
  - action: text.set_value
    metadata: {}
    target:
      entity_id: "{{text}}"
    data:
      value: "{{url}}"

  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: "{{switch}}"
    data: {} 


  
